apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    role: wordpress
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: wordpress 
    spec:
      containers:
      - name: wordpress 
        image: hansleolml/demo_spring:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080    