apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress 
    spec:
      containers:
      - name: wordpress 
        image: hansleolml/demo_spring:latest
        ports:
        - containerPort: 8080